spring.application.name=SmartQueueManagement

# Firebase Configuration
# Note: Google Application Credentials should be handled via src/main/resources/serviceAccountKey.json

# Server Port
server.port=8080

# Logging Level
logging.level.com.google.cloud.firestore=INFO
